blog/urls.py
from django.views.decorators.cache import cache_page
from blog.apps import BlogConfig
from django.urls import path
from blog.views import BlogCreateView, BlogListView, BlogDetailView, BlogUpdateView, BlogDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('blog/create/', BlogCreateView.as_view(), name='create'),
    path('', BlogListView.as_view(), name='list'),
    path('blog/view/<int:pk>/',cache_page(60)(BlogDetailView.as_view()), name='view'),
    path('blog/edit/<int:pk>/', BlogUpdateView.as_view(), name='edit'),
    path('blog/delete/<int:pk>/', BlogDeleteView.as_view(), name='delete'),

]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('distribution/', include('distribution.urls', namespace='distribution')),
                  path('users/', include('users.urls', namespace='users')),
                  path('', include('blog.urls', namespace='blog')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

NULLABLE = {'blank': True, 'null': True}


class Blog(models.Model):
    title = models.CharField(max_length=150, **NULLABLE, verbose_name='Заголовок')
    slug = models.CharField(max_length=255, **NULLABLE, unique=True, verbose_name='Ссылка')
    content = models.TextField(**NULLABLE, verbose_name='Содержимое')
    image = models.ImageField(upload_to='statistic/', **NULLABLE, verbose_name='Превью')
    creation_date = models.DateField(**NULLABLE, verbose_name='Дата создания')
    publication_feature = models.BooleanField(default=True, verbose_name='Признак публикации')
    views_count = models.PositiveIntegerField(verbose_name='Количество просмотров', default=0, editable=False)

    def __str__(self):
        return f'{self.title}: {self.views_count}'

    class Meta:
        verbose_name = 'блог'
        verbose_name_plural = 'блоги'

blog/forms.py
from django import forms

from blog.models import Blog
from users.forms import StyleFormMixin


class BlogForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Blog
        fields = ('title', 'content', 'image', 'creation_date', 'publication_feature')

blog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.shortcuts import render
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView
from pytils.translit import slugify
from blog.forms import BlogForm
from blog.models import Blog
from distribution.models import Distribution, DistributionClient


class BlogCreateView(LoginRequiredMixin, CreateView):
    model = Blog
    form_class = BlogForm
    success_url = reverse_lazy('blog:list')

    def form_valid(self, form):
        if form.is_valid():
            new_stat = form.save()
            new_stat.slug = slugify(new_stat.title)
            new_stat.save()
        return super().form_valid(form)


class BlogUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    model = Blog
    form_class = BlogForm
    permission_required = 'blog.change_blog'

    # success_url = reverse_lazy('blog:list')

    def form_valid(self, form):
        if form.is_valid():
            new_stat = form.save()
            new_stat.slug = slugify(new_stat.title)
            new_stat.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('blog:view', args=[self.kwargs.get('pk')])


class BlogDeleteView(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    model = Blog
    success_url = reverse_lazy('blog:list')
    permission_required = 'blog.delete_blog'


class BlogListView(ListView):
    model = Blog

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        queryset = queryset.filter(publication_feature=True)
        return queryset

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['distribution_count'] = Distribution.objects.all().count()
        context_data['active_distribution_count'] = Distribution.objects.filter(
            status=Distribution.status_started).count()
        context_data['count_unique_distribution_client'] = DistributionClient.objects.all().count()
        context_data['blog_list'] = Blog.objects.all().order_by('?')[:3]
        return context_data


class BlogDetailView(DetailView):
    model = Blog

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.views_count += 1
        self.object.save(update_fields=['views_count'])

        return self.object

blog/templates/blog/blog_confirm_delete.html
{% extends 'distribution/base.html' %}

{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <p>Хотите удалить Блог?</p>
                        <button type="submit" class="btn btn-danger">Подтвердить</button>
                        <a href="{% url 'blog:list' %}" class="btn btn-outline-secondary">Отмена</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/blog_detail.html
{% extends 'distribution/base.html' %}

{% block content %}
{% load static %}
{% load my_tags %}
<div class="row">
    <div class="col-md-4">
        <h2>Название: {{object.title}}</h2>
        <img src="{{ object.image|my_media }}" alt="PC" style="width: 350px; height: 225px;">
        <p>Slug: {{object.slug}}</p>
        <p>Контент: {{object.content}}</p>
        <p>Признак публикации: {{object.publication_feature}}</p>
        <p>Просмотры: {{ object.views_count }}</p>
        <a href="{% url 'blog:edit' object.pk %}" class="btn btn-success">Update</a>
        <a href="{% url 'blog:list' %}" class="btn btn-secondary">Back</a>
    </div>
</div>
{% endblock %}

blog/templates/blog/blog_form.html
{% extends 'distribution/base.html' %}

{% block content %}
<div class="row">
    <div class="col-3"></div>
    <div class="col-6">
        <div class="card">
            <div class="card-header">Рассылка</div>
            <div class="card-body">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-outline-primary">
                        {% if object %}
                        Сохранить
                        {% else %}
                        Создать
                        {% endif %}
                    </button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/blog_list.html
{% extends 'distribution/base.html' %}

{% block content %}
{% load my_tags %}
{% include 'distribution/includes/distribution_info.html' %}
<div class="col-12 mb-5">
    <a class="btn btn-success" href="{% url 'blog:create' %}">Добавить блог</a>
</div>
<div class="row">
    {% for object in object_list %}
    <div class="col-md-4">
        <h2>{{object.title}}</h2>
        <h5 class="text text-primary">{{object.slug}}</h5>
        <img src="{{ object.image|my_media }}" alt="PC" style="width: 350px; height: 225px;">
        <p>{{object.description}}</p>
        <div class="btn-group mb-5">
            <a href="{% url 'blog:view' object.pk %}" class="btn btn-outline-white active"
               aria-current="page">Просмотр</a>
            {% if perms.blog.change_blog %}
            <a href="{% url 'blog:edit' object.pk %}" class="btn btn-outline-success">Обновить</a>
            {% endif %}
            {% if perms.blog.delete_blog %}
            <a href="{% url 'blog:delete' object.pk %}" class="btn btn-danger">Удалить</a>
            {% endif %}
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}