blog/urls.py
from django.views.decorators.cache import cache_page
from blog.apps import BlogConfig
from django.urls import path
from blog.views import BlogCreateView, BlogListView, BlogDetailView, BlogUpdateView, BlogDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('blog/create/', BlogCreateView.as_view(), name='create'),
    path('', BlogListView.as_view(), name='list'),
    path('blog/view/<int:pk>/',cache_page(60)(BlogDetailView.as_view()), name='view'),
    path('blog/edit/<int:pk>/', BlogUpdateView.as_view(), name='edit'),
    path('blog/delete/<int:pk>/', BlogDeleteView.as_view(), name='delete'),

]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('distribution/', include('distribution.urls', namespace='distribution')),
                  path('users/', include('users.urls', namespace='users')),
                  path('', include('blog.urls', namespace='blog')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from users.apps import UsersConfig
from users.views import LoginView, LogoutView, RegisterView, UserUpdateView, generate_password, UsersListView, \
    UserDetailView

app_name = UsersConfig.name

urlpatterns = [
    path('users/', UsersListView.as_view(), name='users_list'),
    path('users/<int:pk>/', UserDetailView.as_view(), name='users_detail'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', UserUpdateView.as_view(), name='profile'),
    path('profile/genpassword/', generate_password, name='generate_password'),

]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

NULLABLE = {'blank': True, 'null': True}


class Users(AbstractUser):
    username = None

    email = models.EmailField(max_length=250,unique=True, verbose_name='Адрес электронной почты')
    first_name = models.CharField(max_length=100, **NULLABLE, verbose_name='Имя')
    last_name = models.CharField(max_length=100, **NULLABLE, verbose_name='Фамилия')
    avatar = models.ImageField(upload_to='users/', **NULLABLE, verbose_name='Аватар')
    comment = models.TextField(**NULLABLE, verbose_name='Описание')

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    def str(self):
        return f'{self.first_name} {self.last_name}: {self.email}'

    class Meta:
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'

users/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django import forms
from users.models import Users


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class UsersRegisterForm(StyleFormMixin, UserCreationForm):
    class Meta:
        model = Users
        fields = ('first_name', 'last_name', 'avatar', 'email', 'password1', 'password2')


class UsersForm(StyleFormMixin, UserChangeForm):
    class Meta:
        model = Users
        fields = ('email', 'password', 'avatar', 'first_name', 'last_name', 'comment')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['password'].widget = forms.HiddenInput()

users/views.py
import random
from django.conf import settings
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.core.mail import send_mail
from django.db.models import Q
from django.shortcuts import render, redirect
from django.contrib.auth.views import LoginView as BaseLoginView
from django.contrib.auth.views import LogoutView as BaseLogoutView
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, UpdateView, DetailView, ListView, DeleteView
from users.forms import UsersRegisterForm, UsersForm
from users.models import Users


class UsersListView(LoginRequiredMixin, ListView):
    model = Users

    def get_queryset(self):
        query = self.request.GET.get('q')
        if query:
            return Users.objects.filter(Q(first_name__icontains=query) | Q(email__icontains=query))
        else:
            return Users.objects.all()


class UserDetailView(LoginRequiredMixin, DetailView):
    model = Users
    template_name = 'users/users_detail.html'
    context_object_name = 'users'


class LoginView(BaseLoginView):
    template_name = 'users/login.html'


class LogoutView(BaseLogoutView):
    pass


class RegisterView(CreateView):
    model = Users
    form_class = UsersRegisterForm
    success_url = reverse_lazy('users:login')
    template_name = 'users/register.html'


    def form_valid(self, form):
        new_user = form.save()
        send_mail(
            subject='Добро пожаловать на наш сайт!',
            message='Поздравляем с регистрацией на нашей платформе!',
            from_email=settings.EMAIL_HOST_USER,
            recipient_list=[new_user.email]
        )
        return super().form_valid(form)


class UserUpdateView(LoginRequiredMixin, UpdateView):
    model = Users
    success_url = reverse_lazy('users:users_list')
    form_class = UsersForm

    def get_object(self, queryset=None):
        return self.request.user


def generate_password(request):
    password = ''.join([str(random.randint(0, 9)) for _ in range(12)])

    send_mail(
        subject='Восстановление пароля',
        message=f'Ваш новый пароль: {password}',
        from_email=settings.EMAIL_HOST_USER,
        recipient_list=[request.user.email]
    )

    request.user.set_password(password)
    request.user.save()
    return redirect(reverse('users:login'))

users/templates/users/base.html
{% load static %}


<!doctype html>
<html lang="en" data-bs-theme="auto">
<head>
    <script src="{% static 'js/color-modes.js' %}"></script>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.115.4">
    <title>Сервис рассылок</title>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
            integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
            crossorigin="anonymous"></script>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <link href="{% static 'css/navbars-offcanvas.css' %}" rel="stylesheet">

    <style>
        body {
            background-image: url("{% static 'img/12.jpg' %}");
            background-size: cover;
            background-color: rgba(0);
            }
    </style>

</head>
<body>
<main>

    <nav class="navbar navbar-expand-lg fixed-top navbar-dark " aria-label="Main navigation">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'users:index' %}">DS</a>
            <button class="navbar-toggler p-0 border-0" type="button" id="navbarSideCollapse"
                    aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="navbar-collapse offcanvas-collapse" id="navbarsExampleDefault">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'users:index' %}">Главная</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:users_list' %}">Профили</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" data-bs-toggle="dropdown" aria-expanded="false">Меню</a>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item" href="#">Контакты</a></li>
                            <li><a class="dropdown-item" href="#">Логи</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
            <form class="d-flex" action="#" method="get">
                <input class="form-control me-2" type="text" placeholder="Поиск" name="q" aria-label="Поиск">
                <button class="btn btn-outline-danger" type="submit">Поиск</button>
            </form>

        </div>
    </nav>

    <div class="container my-5">
        <div class="bg">
            <div class="col-sm-10 py-5 mx-auto">
                <h1 class="display-5 fw-normal text-danger">Сервис рассылок</h1>
                <h5 class="display-5 fw-normal text-white">Сервис предназначен для автоматической рассылки уведомлений
                    пользователям</h5>
                <a class="btn btn-outline-danger" href="#" role="button">Информация</a>
            </div>
        </div>
    </div>
    {% block content %}
    {% endblock %}

</main>

<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
<script src="{%static 'js/popper.min.js' %}"></script>
<script src="{%static 'js/bootstrap.min.js' %}"></script>

</body>
</html>

users/templates/users/login.html
{% extends 'distribution/base.html' %}

{% block content %}
<div class="row">
    <div class="col-3"></div>
    <div class="col-6">
        <div class="card">
            <div class="card-header"></div>
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-outline-primary">Вход</button>
                </form>
            </div>
            <div class="card-footer"></div>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/register.html
{% extends 'distribution/base.html' %}

{% block content %}
    <div class="row">
        <div class="col-3"></div>
        <div class="col-6">
            <div class="card">
                <div class="card-header"></div>
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-outline-primary">Регистрация</button>
                    </form>
                </div>
                <div class="card-footer"></div>
            </div>
        </div>
    </div>
{% endblock %}

users/templates/users/users_confirm_delete.html
{% extends 'distribution/base.html' %}

{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <p>Хотите удалить пользователя "{{object.first_name}} {{object.last_name}}?"</p>
                        <button type="submit" class="btn btn-danger">Подтвердить</button>
                        <a href="{% url 'users:users_list' %}" class="btn btn-outline-secondary">Отмена</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/users_detail.html
{% extends 'distribution/base.html' %}

{% block content %}
{% load static %}
{% load my_tags %}
<div class="row">
    <div class="col-md-4">
        <img src="{{ users.avatar|my_media }}" class="w-100" alt="{{users.first_name}} {{object.last_name}}" height="300">
        <h5 class="mt-0 text-white">Имя пользователя: {{object.first_name}} {{object.last_name}}</h5>
        <h5 class="mt-0 text-warning">Email: {{object.email}}</h5>
        <h5 class="mt-0 text-primary mb-4">Описание: {{users.comment}}</h5>
        {% if perms.users.change_users %}
        <a href="{% url 'users:profile'%}" class="btn btn-outline-success">Обновить информацию</a>
        {% endif %}
        <a href="{% url 'users:users_list' %}" class="btn btn-dark">Назад</a>
    </div>
</div>
{% endblock %}

users/templates/users/users_form.html
{% extends 'distribution/base.html' %}

{% block content %}
<div class="row">
    <div class="col-3"></div>
    <div class="col-6">
        <div class="card">
            <div class="card-header">Мой Профиль</div>
            <div class="card-body">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-outline-primary">Сохранить</button>
                </form>
            </div>
            <div class="card-footer">
                <a href="{% url 'users:generate_password' %}" class="btn btn-success">Сгенерировать пароль</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/users_list.html
{% extends 'distribution/base.html' %}

{% block content %}
{% load static %}
{% load my_tags %}
<div class="my-3 p-3  rounded shadow-sm" xmlns="http://www.w3.org/1999/html">
    <h6 class="border-bottom pb-2 mb-3 text-warning">Пользователи</h6>
    {% if user.is_superuser %}
    <a href="{% url 'users:register' %}" class="btn btn-outline-warning mb-3">Добавить пользователя</a>
    {% endif %}
</div>
<div class="col-6 ">
    <div class="row-auto">
        {% for object in object_list %}

        <div class="row g-0  position-relative">
            <div class="col-md-6 mb-md-0 p-md-4">
                <img src="{{ object.avatar|my_media }}" class="w-100" alt="{{users.first_name}}">
            </div>
            <div class="col-md-6 p-4 ps-md-0">
                <h5 class="mt-0 text-white">Имя пользователя: {{object.first_name}} {{object.last_name}}</h5>
                <h5 class="mt-0 text-warning">Email: {{object.email}}</h5>
                <h5 class="mt-0 text-primary mb-4">Описание: {{object.comment}}</h5>
                <div class="btn-group-small mb-5">
                    {% if perms.users.change_users %}
                    <a href="{% url 'users:users_detail' object.pk %}" class="btn btn-outline-secondary active"
                       aria-current="page">Профиль</a>
                    {% endif %}
                </div>
            </div>
        </div>

        {% endfor %}
    </div>
</div>
{% endblock %}