blog/urls.py
from django.views.decorators.cache import cache_page
from blog.apps import BlogConfig
from django.urls import path
from blog.views import BlogCreateView, BlogListView, BlogDetailView, BlogUpdateView, BlogDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('blog/create/', BlogCreateView.as_view(), name='create'),
    path('', BlogListView.as_view(), name='list'),
    path('blog/view/<int:pk>/',cache_page(60)(BlogDetailView.as_view()), name='view'),
    path('blog/edit/<int:pk>/', BlogUpdateView.as_view(), name='edit'),
    path('blog/delete/<int:pk>/', BlogDeleteView.as_view(), name='delete'),

]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('distribution/', include('distribution.urls', namespace='distribution')),
                  path('users/', include('users.urls', namespace='users')),
                  path('', include('blog.urls', namespace='blog')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

distribution/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from distribution.views import DistributionListView, DistributionDetailView, DistributionCreateView, \
    DistributionUpdateView, DistributionDeleteView, MessageCreateView, DistributionClientListView, \
    DistributionClientCreateView, DistributionClientUpdateView, DistributionClientDeleteView, MessageDeleteView
from distribution.apps import DistributionConfig

app_name = DistributionConfig.name

urlpatterns = [
    path('distribution/', DistributionListView.as_view(), name='distribution_list'),
    path('distribution/<int:pk>/', DistributionDetailView.as_view(), name='distribution_detail'),
    path('create/', DistributionCreateView.as_view(), name='create_distribution'),
    path('update/<int:pk>/', DistributionUpdateView.as_view(), name='update_distribution'),
    path('delete/<int:pk>/', DistributionDeleteView.as_view(), name='distribution_confirm_delete'),
    path('create/message/', MessageCreateView.as_view(), name='create_message'),
    path('delete/message/<int:pk>', MessageDeleteView.as_view(), name='delete_message'),
    path('client/', cache_page(60)(DistributionClientListView.as_view()), name='distribution_client_list'),
    path('client/create', DistributionClientCreateView.as_view(), name='create_distribution_client'),
    path('client/update/<int:pk>', DistributionClientUpdateView.as_view(),
         name='update_distribution_client'),
    path('client/delete/<int:pk>', DistributionClientDeleteView.as_view(),
         name='delete_distribution_client'),
]

users/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from users.apps import UsersConfig
from users.views import LoginView, LogoutView, RegisterView, UserUpdateView, generate_password, UsersListView, \
    UserDetailView

app_name = UsersConfig.name

urlpatterns = [
    path('users/', UsersListView.as_view(), name='users_list'),
    path('users/<int:pk>/', UserDetailView.as_view(), name='users_detail'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', UserUpdateView.as_view(), name='profile'),
    path('profile/genpassword/', generate_password, name='generate_password'),

]

distribution/models.py
from django.db import models
from users.models import NULLABLE


class DistributionClient(models.Model):
    first_name = models.CharField(max_length=100, **NULLABLE, verbose_name='Имя')
    last_name = models.CharField(max_length=100, **NULLABLE, verbose_name='Фамилия')
    email = models.EmailField(max_length=250, **NULLABLE, unique=True, verbose_name='Адрес электронной почты')
    comment = models.TextField(**NULLABLE, verbose_name='Комментарий')

    def __str__(self):
        return f'{self.email} - {self.last_name} {self.first_name}'

    class Meta:
        verbose_name = 'Клиент рассылки'
        verbose_name_plural = 'Клиенты рассылки'


class Message(models.Model):
    subject = models.CharField(max_length=255, verbose_name='Тема сообщения')
    body = models.TextField(**NULLABLE, verbose_name='Текст сообщения')

    def __str__(self):
        return f'{self.subject}: {self.body}'

    class Meta:
        verbose_name = 'Сообщение'
        verbose_name_plural = 'Сообщения'


class Distribution(models.Model):
    sending_frequency_daily = 'daily'
    sending_frequency_weekly = 'weekly'
    sending_frequency_monthly = 'monthly'

    sending_frequency = (
        (sending_frequency_daily, 'daily'),
        (sending_frequency_weekly, 'weekly'),
        (sending_frequency_monthly, 'monthly')
    )

    status_created = 'created'
    status_started = 'started'
    status_completed = 'completed'

    statuses = (
        (status_created, 'created'),
        (status_started, 'started'),
        (status_completed, 'completed')
    )

    start_time = models.DateField(**NULLABLE, verbose_name='Время начала рассылки')
    end_time = models.DateField(**NULLABLE, verbose_name='Время окончания рассылки')
    frequency = models.CharField(max_length=50, choices=sending_frequency, default=sending_frequency_daily,
                                 verbose_name='Период рассылки')
    status = models.CharField(max_length=50, choices=statuses, default=status_created, verbose_name='Статус рассылки')
    message = models.ForeignKey(Message, on_delete=models.CASCADE, **NULLABLE, verbose_name='Сообщение')
    distribution_client = models.ManyToManyField(DistributionClient, verbose_name='Клиент рассылки')
    datetime = models.DateField(auto_now_add=True, **NULLABLE, verbose_name='дата и время попытки')
    attempt = models.BooleanField(default=False, verbose_name='статус попытки')
    feedback = models.TextField(verbose_name='ответ сервера', **NULLABLE)

    def __str__(self):
        return f'{self.frequency} - {self.start_time}'

    class Meta:
        verbose_name = 'Рассылка'
        verbose_name_plural = 'Рассылки'

distribution/forms.py
from django import forms
from users.forms import StyleFormMixin
from .models import Distribution, Message, DistributionClient


class DistributionForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Distribution
        fields = ('start_time', 'end_time', 'frequency', 'status', 'distribution_client', 'message')


class MessageForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Message
        fields = ('subject', 'body')


class DistributionClientForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = DistributionClient
        fields = ('first_name', 'last_name', 'email', 'comment')

distribution/views.py
import datetime
from django.conf import settings
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.core.mail import send_mail
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from blog.models import Blog
from distribution.forms import DistributionForm, MessageForm, DistributionClientForm
from distribution.models import Distribution, Message, DistributionClient


class DistributionListView(LoginRequiredMixin, ListView):
    model = Distribution

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['distribution_count'] = Distribution.objects.all().count()
        context_data['active_distribution_count'] = Distribution.objects.filter(
            status=Distribution.status_started).count()
        context_data['count_unique_distribution_client'] = DistributionClient.objects.all().count()
        context_data['blog_list'] = Blog.objects.all().order_by('?')[:3]
        return context_data


class DistributionDetailView(LoginRequiredMixin, PermissionRequiredMixin, DetailView):
    model = Distribution
    template_name = 'distribution/distribution_detail.html'
    context_object_name = 'distribution'
    permission_required = 'distribution.view_distribution'


class DistributionCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    model = Distribution
    form_class = DistributionForm
    permission_required = 'distribution.add_distribution'
    success_url = reverse_lazy('distribution:distribution_list')

    def form_valid(self, form):

        """
        Проверка текущей даты, с датой начала и окончания рассылки.
        """
        if form.is_valid():
            self.object = form.save()
            self.object.user = self.request.user
            day_today = datetime.date.today()
            if self.object.start_time <= day_today < self.object.end_time:
                self.object.status = 'started'
                mail = self.object.message
                users = self.object.distribution_client.all()
                for user in users:
                    send_mail(
                        subject=mail.subject,
                        message=mail.body,
                        from_email=settings.EMAIL_HOST_USER,
                        recipient_list=[user.email]
                    )
                self.object.datatime = day_today
            elif day_today > self.object.end_time:
                self.object.status = 'completed'
            self.object.save()
            return super().form_valid(form)


class DistributionUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    model = Distribution
    form_class = DistributionForm
    permission_required = 'distribution.change_distribution'
    success_url = reverse_lazy('distribution:distribution_list')

    def form_valid(self, form):

        """
        Проверка текущей даты, с датой начала и окончания рассылки.
        """
        if form.is_valid():
            self.object = form.save()
            self.object.user = self.request.user
            day_today = datetime.date.today()
            if self.object.start_time <= day_today < self.object.end_time:
                self.object.status = 'started'
                mail = self.object.message
                users = self.object.distribution_client.all()
                for user in users:
                    send_mail(
                        subject=mail.subject,
                        message=mail.body,
                        from_email=settings.EMAIL_HOST_USER,
                        recipient_list=[user.email]
                    )
                self.object.datatime = day_today
            elif day_today > self.object.end_time:
                self.object.status = 'completed'
            self.object.save()
            return super().form_valid(form)


class DistributionDeleteView(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    model = Distribution
    success_url = reverse_lazy('distribution:distribution_list')
    permission_required = 'distribution.delete_distribution'


class MessageCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    model = Message
    form_class = MessageForm
    success_url = reverse_lazy('distribution:distribution_list')
    permission_required = 'distribution.add_message'


class MessageDeleteView(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    model = Message
    success_url = reverse_lazy('distribution:distribution_detail')
    permission_required = 'distribution.delete_message'


class DistributionClientListView(LoginRequiredMixin, ListView):
    model = DistributionClient
    template_name = 'distribution/distribution_client_list.html'
    context_object_name = 'client'

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['client_list'] = self.get_queryset()
        return context_data


class DistributionClientCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    model = DistributionClient
    template_name = 'distribution/distribution_client_form.html'
    form_class = DistributionClientForm
    success_url = reverse_lazy('distribution:distribution_client_list')
    permission_required = 'distribution.add_distribution_client'


class DistributionClientUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    model = DistributionClient
    template_name = 'distribution/distribution_client_form.html'
    form_class = DistributionClientForm
    success_url = reverse_lazy('distribution:distribution_client_list')
    permission_required = 'distribution.change_distribution_client'


class DistributionClientDeleteView(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    model = DistributionClient
    template_name = 'distribution/distribution_client_confirm_delete.html'
    success_url = reverse_lazy('distribution:distribution_client_list')
    permission_required = 'distribution.delete_distribution_client'

distribution/templates/distribution/base.html
{% load static %}
{% load my_tags %}

<!doctype html>
<html lang="en" data-bs-theme="auto">
<head>
    <script src="{% static 'js/color-modes.js' %}"></script>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.115.4">
    <title>Сервис рассылок</title>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
            integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
            crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <link href="{% static 'css/navbars-offcanvas.css' %}" rel="stylesheet">


    <style>
        body {
            background-image: url("{% static 'img/12.jpg' %}");
            background-size: cover;
            background-color: rgba(0);
            }
        .auto__table td {
    background-color: transparent;
}
    </style>

</head>
<body>
<main>

    <nav class="navbar navbar-expand-lg fixed-top navbar-dark " aria-label="Main navigation">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">DS</a>
            <button class="navbar-toggler p-0 border-0" type="button" id="navbarSideCollapse"
                    aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="navbar-collapse offcanvas-collapse" id="navbarsExampleDefault">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page"
                           href="{% url 'blog:list' %}">Главная</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page"
                           href="{% url 'distribution:distribution_list' %}">Рассылки</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:users_list' %}">Пользователи</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                           aria-expanded="false">
                            Меню
                        </a>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item" href="#">Контакты</a></li>
                            <li><a class="dropdown-item" href="{% url 'blog:list' %}">К Блогам</a></li>
                            <li><a class="dropdown-item" href="{% url 'distribution:distribution_client_list'%}">Клиенты
                                рассылки</a></li>
                            {% if user.is_authenticated %}
                            <li><a class="dropdown-item" href="{% url 'users:profile' %}">Профиль</a></li>
                            <li><a class="dropdown-item text-danger" href="{% url 'users:logout' %}">Выход</a></li>
                            {% else %}
                            <li><a class="dropdown-item" href="{% url 'users:login' %}">Вход</a></li>
                            <li><a class="dropdown-item" href="{% url 'users:register' %}">Регистрация</a></li>
                            {% endif %}
                        </ul>
                    </li>
                    {% if user.is_authenticated %}
                    <li class="nav-item active mr-2">
                        <img src="{{ object.avatar|my_media }}" alt="Avatar" width="40" height="40">
                    </li>
                    <li class="nav-item active">
                        <a class="text-warning" href="{% url 'users:profile' %}">{{ user.email }}</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
            <form class="d-flex" action="#" method="get">
                <input class="form-control me-2" type="text" placeholder="Поиск" name="q" aria-label="Поиск">
                <button class="btn btn-outline-danger" type="submit">Поиск</button>
            </form>

        </div>
    </nav>

    <div class="container my-5">
        <div class="bg">
            <div class="col-sm-10 py-5 mx-auto">
                <h1 class="display-5 fw-normal text-danger">Сервис рассылок</h1>
                <h5 class="display-5 fw-normal text-white">Сервис предназначен для автоматической рассылки уведомлений
                    пользователям</h5>
                <a class="btn btn-outline-danger" href="#" role="button">Информация</a>
            </div>
        </div>
    </div>
    {% block content %}
    {% endblock %}

</main>

<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
<script src="{%static 'js/popper.min.js' %}"></script>
<script src="{%static 'js/bootstrap.min.js' %}"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
        integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.min.js"
        integrity="sha384-Rx+T1VzGupg4BHQYs2gCW9It+akI2MM/mndMCy36UVfodzcJcF0GGLxZIzObiEfa"
        crossorigin="anonymous"></script>

</body>
</html>

distribution/templates/distribution/distribution_client_confirm_delete.html
{% extends 'distribution/base.html' %}

{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <p>Хотите удалить клиента "{{object.first_name}} {{object.last_name}}?"</p>
                        <button type="submit" class="btn btn-danger">Подтвердить</button>
                        <a href="{% url 'users:users_list' %}" class="btn btn-outline-secondary">Отмена</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

distribution/templates/distribution/distribution_client_form.html
{% extends 'distribution/base.html' %}

{% block content %}
<div class="row">
    <div class="col-3"></div>
    <div class="col-6">
        <div class="card">
            <div class="card-header">Мой Профиль</div>
            <div class="card-body">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-outline-primary">Сохранить</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

distribution/templates/distribution/distribution_client_list.html
{% extends 'distribution/base.html' %}

{% block content %}
{% load static %}
{% load my_tags %}
<div class="my-3 p-3  rounded shadow-sm" xmlns="http://www.w3.org/1999/html">
    <h6 class="border-bottom pb-2 mb-3 text-warning">Клиенты рассылки</h6>
    {% if perms.distribution.add_distribution_client %}
    <a href="{% url 'distribution:create_distribution_client' %}" class="btn btn-outline-warning mb-3">Добавить
        клиента</a>
    {% endif %}
</div>
<div class="col-6 ">
    <div class="row-auto">
        {% for client in client_list %}


        <h5 class="mt-0 text-white">{{client.first_name}} {{client.last_name}}</h5>
        <strong class="d-block text-warning">{{client.email}}</strong>
        <h5 class="mt-0 text-white">{{client.comment}}</h5>
        <div class="btn-group-small mb-5">
            {% if perms.distribution.change_distribution_client %}
            <a href="{% url 'distribution:update_distribution_client' client.pk %}" class="btn btn-outline-success">Обновить</a>
            {% endif %}
            {% if perms.distribution.delete_distribution_client %}
            <a href="{% url 'distribution:delete_distribution_client' client.pk %}" class="btn btn-outline-danger">Удалить</a>
            {% endif %}
        </div>


        {% endfor %}
    </div>
</div>
{% endblock %}

distribution/templates/distribution/distribution_confirm_delete.html
{% extends 'distribution/base.html' %}

{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <p>Хотите удалить рассылку?</p>
                        <button type="submit" class="btn btn-danger">Подтвердить</button>
                        <a href="{% url 'distribution:distribution_list' %}" class="btn btn-outline-secondary">Отмена</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

distribution/templates/distribution/distribution_detail.html
{% extends 'distribution/base.html' %}

{% block content %}
{% load static %}
{% load distribution_tags %}
<div class="row">
    <div class="col-md-4">
        <img src="{{ distribution.avatar|distribution_media }}" class="w-100" alt="" height="300">
        <h5 class="mt-0 text-white">Время начала рассылки: {{object.start_time}}</h5>
        <h5 class="mt-0 text-white">Время окончания рассылки: {{object.end_time}}</h5>
        <h5 class="d-block text-warning">Переодичность отправки сообщения: {{object.frequency}}</h5>
        <h5 class="mt-0 text-success">Статус: {{object.status}}</h5>
        <h5 class="mt-0 text-white mb-3">Сообщение: {{object.message}}</h5>
        {% if perms.distribution.change_distribution %}
        <a href="{% url 'distribution:update_distribution' object.pk %}" class="btn btn-outline-success">Обновить
            информацию</a>
        {% endif %}
<!--        {% if perms.distribution.delete_message %}-->
<!--        <a href="{% url 'distribution:delete_message' object.pk %}" class="btn btn-outline-danger">Удалить сообщение</a>-->
<!--        {% endif %}-->
        <a href="{% url 'distribution:distribution_list' %}" class="btn btn-dark">Назад</a>
    </div>
</div>
{% endblock %}

distribution/templates/distribution/distribution_form.html
{% extends 'distribution/base.html' %}

{% block content %}
<div class="row">
    <div class="col-3"></div>
    <div class="col-6">
        <div class="card">
            <div class="card-header">Рассылка</div>
            <div class="card-body">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-outline-primary">Сохранить</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

distribution/templates/distribution/distribution_list.html
{% extends 'distribution/base.html' %}

{% block content %}
{% load static %}
{% load distribution_tags %}
{% include 'distribution/includes/distribution_info.html' %}
<div class="my-3 p-3  rounded shadow-sm" xmlns="http://www.w3.org/1999/html">
    <h6 class="border-bottom pb-2 mb-3 text-danger">Рассылки</h6>
    {% if perms.distribution.add_distribution %}
    <a href="{% url 'distribution:create_distribution' %}" class="btn btn-outline-warning mb-3">Добавить рассылку</a>
    {% endif %}
    {% if perms.distribution.add_message %}
    <a href="{% url 'distribution:create_message' %}" class="btn btn-outline-success mb-3">Создать
        сообщение</a>
    {% endif %}
</div>
<div class="col-6 ">
    <div class="row-auto">
        {% for object in object_list %}
        <div class="row g-0  position-relative">
            <div class="col-md-6 mb-md-0 p-md-4">
                <img src="{{ object.avatar|distribution_media }}" class="w-100" alt="{{distribution}}">
            </div>
            <div class="col-md-6 p-4 ps-md-0">
                <h5 class="mt-0 text-secondary">Рассылка №{{object.id}}</h5>
                <h5 class="mt-0 text-white">Время начала рассылки: {{object.start_time}}</h5>
                <h5 class="mt-0 text-white">Время окончания рассылки: {{object.end_time}}</h5>
                <h5 class="d-block text-warning">Переодичность отправки сообщения: {{object.frequency}}</h5>
                <!--                <h5 class="d-block text-danger">Клиенты рассылки: {{object.distribution_client}}</h5>-->
                <h5 class="mt-0 text-success">Статус: {{object.status}}</h5>
                <h5 class="mt-0 text-white">Сообщение: {{object.message}}</h5>
                <div class="btn-group-small mb-5">
                    {% if perms.distribution.view_distribution %}
                    <a href="{% url 'distribution:distribution_detail' object.pk %}"
                       class="btn btn-outline-primary"
                       aria-current="page">Информация</a>
                    {% endif %}
                    {% if perms.distribution.change_distribution %}
                    <a href="{% url 'distribution:update_distribution' object.pk %}" class="btn btn-outline-success">Обновить</a>
                    {% endif %}
                    {% if perms.distribution.delete_distribution %}
                    <a href="{% url 'distribution:distribution_confirm_delete' object.pk %}"
                       class="btn btn-outline-danger">Удалить</a>
                    {% endif %}
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

distribution/templates/distribution/message_confirm_delete.html
{% extends 'distribution/base.html' %}

{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <p>Хотите удалить сообщение?</p>
                        <button type="submit" class="btn btn-danger">Подтвердить</button>
                        <a href="{% url 'distribution:distribution_list' %}" class="btn btn-outline-secondary">Отмена</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

distribution/templates/distribution/message_form.html
{% extends 'distribution/base.html' %}

{% block content %}
<div class="row">
    <div class="col-3"></div>
    <div class="col-6">
        <div class="card">
            <div class="card-header">Создание сообщения для рассылки</div>
            <div class="card-body">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-outline-primary">Сохранить</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}